import Link from 'next/link';

const builds = [
  { no: '01', title: 'Proprietary products', text: 'AI and robotic products designed for families, education, industry and global markets.', href: '/products' },
  { no: '02', title: 'Technology integration', text: 'Robotics, AI, data and automation integrated around real operating requirements.', href: '/solutions' },
  { no: '03', title: 'Global commercialization', text: 'Localization, manufacturing, distribution and service partnerships across markets.', href: '/partners' },
];

const capabilities = [
  { eyebrow: 'ROBOTICS', title: 'Robotics for industry and everyday life.', text: 'Industrial systems, compact humanoid platforms, companion robots and intelligent human–robot interaction.', href: '/robotics', image: '/images/hero-robotics.webp' },
  { eyebrow: 'ARTIFICIAL INTELLIGENCE', title: 'AI that becomes a product.', text: 'Computer vision, AI agents, multimodal interfaces, predictive systems and intelligent automation.', href: '/ai', image: '/images/ai-computer-vision.webp' },
  { eyebrow: 'DATA & DATASETS', title: 'Specialized data for next-generation AI.', text: 'Real-world datasets, annotation pipelines and structured data for robotics, vision and embodied AI.', href: '/data', image: '/images/data-lidar-capture.webp' },
];

const industries = [['Manufacturing', 'manufacturing'], ['Logistics & Warehousing', 'logistics'], ['Construction', 'construction'], ['Retail & Service', 'retail-service'], ['Hospitality', 'hospitality'], ['Energy', 'energy'], ['Agriculture', 'agriculture']];
const process = ['Discovery', 'Analysis', 'Solution Design', 'Technology Selection', 'Pilot Project', 'Integration', 'Scale', 'Support'];

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-image"/><div className="hero-content wrap"><p className="eyebrow">AI <i>·</i> ROBOTICS <i>·</i> PRODUCTS</p><h1>AI. Robotics.<br /><em>Products of the Future.</em></h1><p className="hero-copy">We develop, integrate and commercialize intelligent robotic systems and AI products for global markets.</p><p className="hero-copy hero-copy-secondary">From humanoid robotics and AI companions to industrial automation, datasets and intelligent business systems.</p><div className="hero-actions"><Link className="button button-primary" data-analytics="hero_products" href="/products">Explore our products <span>↗</span></Link><a className="button button-outline" data-analytics="hero_email" href="mailto:sergey@novatek-international.com?subject=NOVATEK%20meeting%20request">Book a meeting <span>↗</span></a></div><p className="hero-signature">We build, integrate and commercialize AI and robotic technologies for global markets.</p></div><div className="hero-index"><span>EUROPE · UKRAINE · CHINA · GLOBAL</span><span>TECHNOLOGY BETWEEN EUROPE AND ASIA</span></div></section>

    <section className="section section-paper builds-section"><div className="wrap"><div className="section-heading split-heading" data-reveal><div><p className="eyebrow eyebrow-dark">WHAT NOVATEK BUILDS</p><h2>From technology concept<br />to global market.</h2></div><p className="body-copy">NOVATEK brings product development, integration and international partnerships into one commercial ecosystem.</p></div><div className="build-grid">{builds.map((item) => <Link className="build-card" data-reveal href={item.href} key={item.no}><span>{item.no}</span><h3>{item.title}</h3><p>{item.text}</p><i>↗</i></Link>)}</div></div></section>

    <section className="product-feature"><div className="product-feature-image"/><div className="wrap product-feature-content"><div data-reveal><p className="eyebrow">OUR PRODUCTS · COMING SOON</p><h2>NOVATEK Kids<br />AI Companion</h2><p>A new generation of safe humanoid AI companions designed for children, education and families.</p><strong>Development Program — 2026/2027</strong><div className="hero-actions"><Link className="button button-primary" href="/kids-ai-companion">Explore the product <span>↗</span></Link><a className="button button-outline" href="mailto:robotics@novatek-international.com?subject=NOVATEK%20Kids%20AI%20Companion%20waitlist">Join the waitlist <span>↗</span></a></div></div></div></section>

    <section className="section section-paper capability-section"><div className="wrap"><div className="section-heading" data-reveal><p className="eyebrow eyebrow-dark">TECHNOLOGY PLATFORM</p><h2>Robotics, AI and data.<br />Designed to work together.</h2></div><div className="capability-list">{capabilities.map((item, index) => <article className="capability-row" data-reveal key={item.eyebrow}><div className="capability-image" style={{ backgroundImage: `url(${item.image})` }}><span>0{index + 1}</span></div><div><p className="eyebrow eyebrow-dark">{item.eyebrow}</p><h3>{item.title}</h3><p>{item.text}</p><Link className="text-link" href={item.href}>Explore {item.eyebrow.toLowerCase()} <span>↗</span></Link></div></article>)}</div></div></section>

    <section className="industry-band"><div className="industry-photo"/><div className="wrap industry-content"><div className="industry-intro" data-reveal><p className="eyebrow">INDUSTRIES</p><h2>Technology shaped<br />around real work.</h2><p>Apply robotics, AI and data to defined processes across production, logistics, construction and service environments.</p><Link className="text-link text-link-light" href="/industries">Explore industries <span>↗</span></Link></div><div className="industry-list">{industries.map(([industry, id], i) => <Link href={`/industries#${id}`} data-reveal key={industry}><span>0{i + 1}</span><b>{industry}</b><i>↗</i></Link>)}</div></div></section>

    <section className="section rnd-section"><div className="wrap rnd-layout"><div data-reveal><p className="eyebrow">R&D · PROPRIETARY TECHNOLOGY</p><h2>Creating NOVATEK intellectual property.</h2><p>NOVATEK develops proprietary AI, robotic interaction systems, multimodal interfaces and specialized datasets for next-generation robotics.</p><Link className="button button-light" href="/ai">Explore research directions <span>↗</span></Link></div><div className="rnd-topics" data-reveal><span>Embodied AI</span><span>Humanoid robotics</span><span>Multimodal interfaces</span><span>Robotic interaction</span><span>Specialized datasets</span><span>AI agents</span></div></div></section>

    <section className="section section-paper partner-strip"><div className="wrap partner-row"><div data-reveal><p className="eyebrow eyebrow-dark">GLOBAL PARTNERSHIPS</p><h2>Build, manufacture and enter new markets together.</h2><p className="body-copy">We support robotics manufacturers entering Ukraine and Europe, and seek manufacturing partners in China to co-develop compact humanoid robotics and AI companion products.</p><Link className="text-link" href="/partners">Explore partnerships <span>↗</span></Link></div><div className="partner-mark" aria-hidden="true"><span>N</span><small>NOVATEK<br />INTERNATIONAL</small></div></div></section>

    <section className="geo-band"><div className="wrap geo-layout" data-reveal><p>EUROPE</p><span>↔</span><p>ASIA</p><div><strong>Europe · Ukraine · China · Global</strong><small>Connecting technology between Europe and Asia.</small></div></div></section>

    <section className="process-section"><div className="wrap process-wrap"><div data-reveal><p className="eyebrow">HOW WE WORK</p><h2>From first question<br />to operational scale.</h2><p className="process-copy">A clear path from understanding the opportunity to integrating, commercializing and supporting the result.</p><Link className="text-link text-link-light" href="/about">Our approach <span>↗</span></Link></div><div className="process-steps">{process.map((step, i) => <div className="process-step" data-reveal key={step}><span>0{i + 1}</span><b>{step}</b></div>)}</div></div></section>

    <section className="section section-paper leadership-section"><div className="wrap leadership-layout"><div className="leadership-portrait" aria-label="Founder portrait placeholder"><span>SS</span><small>FOUNDER & CEO</small></div><div data-reveal><p className="eyebrow eyebrow-dark">LEADERSHIP</p><h2>Sergey Sergov</h2><h3>Founder & CEO</h3><p className="body-copy">Building NOVATEK at the intersection of AI, robotics, data and global technology partnerships.</p><a className="text-link" href="mailto:sergey@novatek-international.com">Contact Sergey <span>↗</span></a></div></div></section>

    <section className="latest-section"><div className="wrap latest-layout"><div data-reveal><p className="eyebrow">LATEST PROJECT · COMING SOON</p><h2>NOVATEK Kids AI Companion</h2><p>Follow the 2026/2027 development program, join the early waitlist or discuss manufacturing, technology and distribution partnerships.</p></div><div className="latest-actions"><a className="button button-primary" href="mailto:robotics@novatek-international.com?subject=NOVATEK%20Kids%20AI%20Companion%20waitlist">Join the waitlist <span>↗</span></a><a className="button button-outline" href="mailto:partnerships@novatek-international.com?subject=NOVATEK%20Kids%20AI%20Companion%20partnership">Partner with us <span>↗</span></a></div></div></section>

    <section className="contact-band"><div className="wrap contact-row"><div data-reveal><p className="eyebrow">GET IN TOUCH</p><h2>Let’s build the future together.</h2><p>Discuss a product, technology integration or international partnership.</p></div><div className="contact-meta"><span>Sergey Sergov · Founder & CEO</span><a href="mailto:sergey@novatek-international.com">sergey@novatek-international.com ↗</a><a href="mailto:partnerships@novatek-international.com">partnerships@novatek-international.com ↗</a><a href="tel:+380968868184">+380 96 886 81 84</a></div><Link className="button button-light" href="/contact">Contact NOVATEK <span>↗</span></Link></div></section>
  </main>;
}
