import Link from 'next/link';

const pillars = [
  { no: '01', title: 'Artificial Intelligence', text: 'Computer vision, predictive analytics and intelligent automation for operational teams.', href: '/ai', image: '/images/ai-computer-vision.webp', tag: 'Intelligence' },
  { no: '02', title: 'Robotics & Automation', text: 'Robotic systems selected, integrated and supported around real work.', href: '/robotics', image: '/images/hero-robotics.webp', tag: 'Automation' },
  { no: '03', title: 'Data & Datasets', text: 'Structured, reliable data for robotics, computer vision and industrial AI.', href: '/data', image: '/images/data-lidar-capture.webp', tag: 'Data systems' },
];
const industries = [['Manufacturing', 'manufacturing'], ['Logistics & Warehousing', 'logistics'], ['Construction', 'construction'], ['Retail & Service', 'retail-service'], ['Hospitality', 'hospitality'], ['Energy', 'energy'], ['Agriculture', 'agriculture']];
const process = ['Discovery', 'Analysis', 'Solution Design', 'Technology Selection', 'Pilot Project', 'Integration', 'Scale', 'Support'];

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-image"/><div className="hero-content wrap"><p className="eyebrow">AI <i>·</i> ROBOTICS <i>·</i> DATA SOLUTIONS</p><h1>Intelligent automation<br />for manufacturing<br /><em>and logistics.</em></h1><p className="hero-copy">We help operational teams reduce repetitive work, improve quality control and scale critical processes through practical AI, robotics and data solutions.</p><div className="hero-actions"><Link className="button button-primary" data-analytics="hero_solutions" href="/solutions">Explore our solutions <span>↗</span></Link><a className="button button-outline" data-analytics="hero_email" href="mailto:sergey@novatek-international.com?subject=NOVATEK%20project%20enquiry">Discuss a project <span>↗</span></a></div><p className="hero-signature">Partnership focus across Europe, Asia and international markets.</p></div><div className="hero-index"><span>01 / 03</span><span>ENGINEERED FOR THE REAL WORLD</span></div></section>

    <section className="trust-strip" aria-label="How NOVATEK builds confidence"><div className="wrap trust-grid"><div><strong>Business-first pilots</strong><span>Validate the workflow and success criteria before scaling.</span></div><div><strong>Technology selection</strong><span>Choose robots, models, sensors and software around the process.</span></div><div><strong>International partnerships</strong><span>Build cooperation with manufacturers and specialists across Europe and Asia.</span></div><div><strong>Lifecycle support</strong><span>Continue from deployment and training through service and development.</span></div></div></section>

    <section className="section section-paper"><div className="wrap"><div className="section-heading split-heading" data-reveal><div><p className="eyebrow eyebrow-dark">OUR SOLUTIONS</p><h2>End-to-end technology<br />for measurable operations.</h2></div><div><p className="body-copy">Start with a defined business challenge. Validate the approach through a controlled pilot, then integrate and scale the solution.</p><Link className="text-link" href="/solutions">Explore all solutions <span>↗</span></Link></div></div><div className="solution-grid">{pillars.map((card) => <Link href={card.href} className="solution-card" data-reveal key={card.no}><div className="solution-image" role="img" aria-label={`${card.title} solution`} style={{ backgroundImage: `url(${card.image})` }}><span>{card.tag}</span><b>{card.no}</b></div><div className="solution-card-body"><h3>{card.title}</h3><p>{card.text}</p><span className="card-arrow">↗</span></div></Link>)}</div></div></section>

    <section className="industry-band"><div className="industry-photo"/><div className="wrap industry-content"><div className="industry-intro" data-reveal><p className="eyebrow">INDUSTRIES</p><h2>Start with the process<br />that matters most.</h2><p>Explore practical applications for production, warehousing, inspection and service operations.</p><Link className="text-link text-link-light" href="/industries">Explore industries <span>↗</span></Link></div><div className="industry-list">{industries.map(([industry, id], i) => <Link href={`/industries#${id}`} data-reveal key={industry}><span>0{i + 1}</span><b>{industry}</b><i>↗</i></Link>)}</div></div></section>

    <section className="section about-home"><div className="wrap about-layout"><div className="about-copy" data-reveal><p className="eyebrow eyebrow-dark">ABOUT NOVATEK</p><h2>Global partner<br />for practical<br />technology delivery.</h2><p className="body-copy">NOVATEK International combines technical expertise with a business-oriented implementation process. We support manufacturers, operators and technology partners from assessment through pilot, deployment and lifecycle service.</p><Link className="button button-dark" href="/about">Learn more about us <span>↗</span></Link></div><div className="about-image" role="img" aria-label="Automated logistics operation"><div className="about-image-overlay"><span>01</span><p>INTELLIGENCE<br />IN MOTION</p></div></div><div className="about-facts" data-reveal><div><strong>End-to-end</strong><span>Partnership from first analysis through support</span></div><div><strong>Real-world</strong><span>Solutions designed around operational constraints</span></div><div><strong>International</strong><span>Partnership development across Europe and Asia</span></div></div></div></section>

    <section className="process-section"><div className="wrap process-wrap"><div data-reveal><p className="eyebrow">HOW WE WORK</p><h2>From first question<br />to operational scale.</h2><p className="process-copy">A clear path from understanding the business to integrating and supporting the solution.</p><Link className="text-link text-link-light" href="/about">Our approach <span>↗</span></Link></div><div className="process-steps">{process.map((step, i) => <div className="process-step" data-reveal key={step}><span>0{i + 1}</span><b>{step}</b></div>)}</div></div></section>

    <section className="section section-paper partner-strip"><div className="wrap partner-row"><div data-reveal><p className="eyebrow eyebrow-dark">GLOBAL PARTNERSHIPS</p><h2>Enter new markets and build technology together.</h2><p className="body-copy">We welcome collaboration with robotics manufacturers, AI companies, system integrators and research organizations seeking practical deployment and market development.</p><Link className="text-link" href="/partners">Explore partnerships <span>↗</span></Link></div><div className="partner-mark" aria-hidden="true"><span>N</span><small>NOVATEK<br />INTERNATIONAL</small></div></div></section>

    <section className="contact-band"><div className="wrap contact-row"><div data-reveal><p className="eyebrow">GET IN TOUCH</p><h2>Choose a process to improve.</h2><p>Tell us what needs to be automated, inspected, predicted or scaled.</p></div><div className="contact-meta"><span>Sergey Sergov · Founder & CEO</span><a data-analytics="home_email" href="mailto:sergey@novatek-international.com">sergey@novatek-international.com ↗</a><a data-analytics="home_phone" href="tel:+380671234567">+380 67 123 45 67</a></div><a className="button button-light" data-analytics="home_discuss_project" href="mailto:sergey@novatek-international.com?subject=NOVATEK%20project%20enquiry">Discuss your project <span>↗</span></a></div></section>
  </main>;
}
